name: crosland_1
favicon: null
layout_spectrum: 0.81711
typography_spectrum: 0.7741930331103504
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6924123372882605
  lightness: 0.25
  saturation: 0.5134228866081685
  rhythmicContrast: 0.6993159395642579
purpose: []
